---
title: "ECB3DSL_code"
output: html_document
editor_options: 
  chunk_output_type: console
---

LOGISTIC REGRESSION
```{r}
library(readr)
divorce_logreg <- read_csv("divorce.csv") 


# reverse scales of non-negatively phrased questions
divorce_logreg [, c(1:5, 8:30, 52, 54)] <- 4 - divorce_linreg [, c(1:5, 8:30, 52, 54)]


# rename columns
names(divorce_logreg) <- c(paste0("Q", 1:54), "Divorce")


# Linear regression on all categories
logreg <- glm(Divorce ~ ., data = divorce_logreg, family = "binomial")
coef(logreg)

```



# CORRELATION PLOT
```{r}
library(corrplot)

# load data
correlation_data <- divorce_logreg

# transform to matrix
correlation_matrix <- as.matrix(cor(correlation_data))
View(correlation_matrix)

# correlation plot
corrplot(correlation_matrix, method = "circle", 
         tl.cex = 0.45, 
         number.cex = 0.45)

```


PCA
```{r}
library(factoextra)

# load correlation matrix data
pca_divorce <- correlation_matrix

# PCA on correlation matrix
pca_results <-  prcomp(pca_divorce[,-55], 
              center = TRUE,
              scale = TRUE)

# eigenvalue>1
eigenvalues <- pca_results$sdev^2

eigenvalue_rule <- sum(eigenvalues > 1)

# PCA summary
summary(pca_results)

pca_results$rotation[,1]


# PCA screeplot
fviz_eig(pca_results,
         addlabels = TRUE)

# PCA biplot
fviz_pca_biplot(pca_results,
                label = "var")
```


LASSO
```{r}
library(glmnet)
library(caret)
library(magrittr)
library(readr)
library(ggplot2)
library(lattice)

# load data
divorce_lasso <- read_csv("divorce.csv") 


# reverse scales of non-negatively phrased questions
divorce_lasso [, c(1:5, 8:30, 52, 54)] <- 4 - divorce_lasso [, c(1:5, 8:30, 52, 54)]


# rename columns
names(divorce_lasso) <- c(paste0("Q", 1:54), "Divorce")

divorce_lasso <-  divorce_lasso[, -c(1:6,8:42,44, 48:51,53,54)]

# divorce_lasso <-  divorce_lasso[, -c(1:4,6:8, 10:16, 18, 21:28, 30:54)]

set.seed(45)
# training 
train_data <- createDataPartition(divorce_lasso$Divorce, 
                                  p = 0.7, 
                                  list = FALSE)

divorce_train <- divorce_lasso[train_data, ]

# testing
divorce_test <- divorce_lasso[-train_data, ]

x_train <- model.matrix(Divorce ~ ., data = divorce_train)

# removal intercept column
x_train <- x_train[, -1]



cv_result <- cv.glmnet(x_train, divorce_train$Divorce,
                       nfolds = 15)
# best lambda
best_lambda <- cv_result$lambda.min

# lasso reg fit
lasso_fit <- glmnet(x_train, divorce_train$Divorce, 
                    family = "binomial", 
                    alpa = 1, 
                    lambda = best_lambda)

glm(Divorce ~ .,family = "binomial", data = divorce_lasso)

# lasso coefficients
coef(lasso_fit)


# cross validation plot
plot(cv_result)



# make predictions
predictions <- predict(cv_result, divorce_test, type = "response")
head(predictions)


threshold <- 0.5
predicted_outcome <- ifelse(predictions > threshold, 1, 0 )

# model accuracy
accuracy <- sum(predicted_outcome == divorce_test$Divorce) / nrow(Test)
cat("Accuracy:", accuracy, "\n")

```



RANDOM FOREST
```{r}
library(stats)
library(glmnet)
library(randomForest)
library(caret)

# load data
divorce_rmf <- divorce_categorical2


divorce_rmf$Divorce <- as.factor(divorce_rmf$Divorce)

# training
train_rmf <- createDataPartition(divorce_rmf$Divorce, p = 0.7, 
                                 list = FALSE)


rmf_train <- divorce_rmf[train_data, ]


# testing
rmf_test <- divorce_rmf[-train_data, ]

# confirm dimensions
dim(rmf_test)
dim(rmf_train)


# Random Forest
(RMF <- randomForest(Divorce ~ ., data = rmf_train))


# prediction and confusion matrix on training data
p1 <- predict(RMF, rmf_train)
confusionMatrix(p1, rmf_train$Divorce)
plot(p1)

# prediction and confusion matrix on test data
p2 <- predict(RMF, rmf_test)
confusionMatrix(p2, rmf_test$Divorce)
plot(p2)


# RMF plots
plot(RMF)
importance(RMF)

varImpPlot(RMF,
           sort = T,
           n.var = 3,
           main = "Top 3 - Variable Importance")


```


BACKWARD SELECTION
```{r}
library(leaps)
library(MASS)

# normal logistic regression
full_regression <- glm(Divorce ~ ., family = "binomial", divorce_dataset)


full_backselection <- stepAIC(full_regression, direction = "backward") 


summary(full_backselection)  


# best model plot
aics <- data.frame(
  aic = c(10,12,14,16,18,20,22),
models = c(4,5,6,7,8,9,10))

library(ggthemes)
ggplot(aics, aes(models, aic)) + geom_point() + geom_line() + theme_linedraw() +
  labs(x = "No of categories", y = "AIC", title = "Backward Selection model AIC's")

# other plots
plot(full_backselection)

   # standard pearson residual described as the standardized distance between observed and expected responses.
   # Standardized pearson residuals are normally distributed with a mean of zero and standard deviation of 1
   # Leverage describes how coefficients would change if some observations are removed
```





DISCRETE INTERVAL DATASET
```{r, message=FALSE}
library(readr)
library(dplyr)



# load discrete interval data set
divorce_discrete <- read_csv("divorce.csv")


# reverse scales of non-negatively phrased questions
divorce_discrete[, c(1:5, 8:30, 52, 54)] <- 4 - divorce_discrete[, c(1:5, 8:30, 52, 54)]


# rename columns
names(divorce_discrete) <- c(paste0("Q", 1:54), "Divorce")

divorce_discrete <- divorce_discrete %>%
  mutate(Divorce = case_when(Divorce == 0 ~ "no",
                             Divorce == 1 ~ "yes"))

View(divorce_discrete)  


```



## CATEGORICAL ORDINAL DATASET
```{r}
# load categorical ordinal data set
divorce_categorical <- divorce_discrete
divorce_categorical2 <- read_csv("divorce.csv")

# Independent variable labels 
divorce_categorical$Divorce <- factor(divorce_categorical$Divorce, 
                                      levels = c(0, 1), 
                                      labels = c("No", "Yes"))


# Dependent variable labels
divorce_categorical2[,-55] <- lapply(divorce_categorical2[,-55], 
                                    function(x) {
  factor(x, levels = c(0, 1, 2, 3, 4), 
         labels = c("Strongly disagree", "Disagree", "Neutral", "Agree", "Strongly agree"))
})

divorce_categorical2[, c(1:5, 8:30, 52, 54)] <- 4 - divorce_categorical2[, c(1:5, 8:30, 52, 54)]


# rename columns
names(divorce_categorical2) <- c(paste0("Q", 1:54), "Divorce")


View(divorce_categorical2)

```



DESCRIPTIVE ANALYSIS
```{r}

# row sum
divorce_discrete <- divorce_discrete %>% 
  mutate(row_sum = rowSums(across(where(is.numeric)))) 


# row mean
divorce_discrete$row_mean <-  (divorce_discrete$row_sum/54) %>% round(2)
 

# category means
summary(divorce_discrete)


# standard deviation
apply (divorce_discrete[, 1:54], 2, sd)


# frequency table of scales (0-4)
apply (divorce_discrete[, 1:54], 2, table)

View(divorce_discrete)

```





# VISUALIZATIONS
```{r}

library(dplyr)
library(ggplot2)
library(ggthemes)

# Divorce frequency and percentages
Divorce_frequency <- divorce_categorical %>% 
  group_by(Divorce) %>% 
  summarize(Frequency = n(),
            Percentage = round(Frequency / nrow(divorce_categorical) * 100, 2))

(Divorce_frequency)


ggplot(Divorce_frequency, aes(Divorce, Frequency)) + 
  geom_bar(stat="identity", position = position_dodge(), fill = c("red", "blue") ) + 
  geom_text(aes(label=Percentage), vjust=1.6, color="white",
            position = position_dodge(0.9),  size=3.5) +
  scale_fill_manual(values = c("red", "blue")) + theme_classic()


```


LIKERT
```{r}
library(likert)
library(ggplot2)
library(xtable)
library(magrittr)


divorce_likert <- divorce_categorical[,c(6,47,49)] %>% as.data.frame()
divorce_likert2 <- divorce_categorical[,-c(55,56,57)] %>% as.data.frame()

headings <- c("Q6, Time Constraints ",
              "Q47, Silent Anger",
              "Q49, Unfounded Accusations")

headings2 <- c(paste0("Q", 1:54))

names(divorce_likert) <- headings
names(divorce_likert2) <- headings2

likert(divorce_likert) %>% plot(type = "bar", legend.position = "right")
likert(divorce_likert2) %>% plot(type = "bar", legend.position = "right")
summary(divorce_likert)
```

